### ISSUE TITLE
addons directory may be redundant

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci-project-template#3]
I've noticed the addons/ directory in my tendenci install and tracked it back to the template. Its empty sans a readme which references the videos module which was moved in tendenci issue #413. I'm not sure what changes to the codebase would be required by removing the directory but form a quick look it seems there wouldn't be much should removal be chosen.

**Comment by eschipul** [comment]
Yes, the addons folder is gone and an "addon" going forward is just another "app". 

We haven't pulled it from the project template because the t5 to t6 to t7 migration has to be done in that order because of django's switch away from south  migrations. I can either leave the "addons" folder in the project template or make a new repo without it for t7. Or rather make a new copy for legacy installs.

Still thinking about that one. I'd like to delete the addon folder personally and put a zip copy (not a .git but just a zip) of that branch with the other backups on our site here (basically a ppa)
https://www.tendenci.com/download/release-archive/

**Comment by goetzk** [comment]
On 5/01/2016 07:12, Ed Schipul wrote:

> Yes, the addons folder is gone and an "addon" going forward is just
> another "app".
> 
> We haven't pulled it from the project template because the t5 to t6 to
> t7 migration has to be done in that order because of django's switch
> away from south migrations. I can either leave the "addons" folder in
> the project template or make a new repo without it for t7. Or rather
> make a new copy for legacy installs.

Perhaps during the interim changing the comment to say 'deprecated,
don't use this it is only for upgrades' will suffice. It will certainly
make it clearer than the existing comments and the loading code for the
last supported call to addons could be removed at the same time.
kk

**Comment by eschipul** [comment]
Great idea. Will do.

**Comment by eschipul** [comment]
@goetzk - directories are back in core.
https://demo.tendenci.com/directories/

In the future I'd love to get back to directories creating a child entityID for each one to track sponsorship money (entities = money / groups = organization and communication). But that is a different issue for the someday/maybe list.
